### ISSUE TITLE
Doesnt work in Opera gx.

### ISSUE THREAD

**Issue by MasterSzefo** [ROBLOX-Plus/Chrome#126] opened 2023-07-26 07:56 UTC
So if you don't add the extension and go to the page the page will load normally but after adding the extension the page won't load.

**Comment by FairwellNoob** [comment] 2023-08-06 14:32
Can vouch.

**Comment by WebGL3D** [comment] 2023-09-02 14:27
Duplicate of #120

**Closed as completed by WebGL3D** 2023-09-02 14:27 UTC
Labels: duplicate
