### ISSUE TITLE
firefox version got banned

### ISSUE THREAD

**Issue by zeroninefourfour** [ROBLOX-Plus/Chrome#31] opened 2021-10-15 11:36 UTC
![圖片](https://user-images.githubusercontent.com/69704016/137480736-a861b6cc-aebf-49ee-a370-7b39ebb753af.png)
IDK why the firefox version got banned, I don't want to use chrome. but I still want use this nice extension

**Comment by juls0730** [comment] 2021-12-18 23:22
there is no official firefox version (see https://github.com/roblox-plus/Chrome/issues/31)

> Roblox+ is not available on Firefox, Edge, or other browsers

this extension was likely banned because it contained malware, please close this issue if the problem is resolved

**Comment by RealCamar** [comment] 2022-01-04 13:19
https://addons.mozilla.org/en-US/firefox/addon/rblx-plus/ is this the *real* extension for Firefox?

**Comment by juls0730** [comment] 2022-01-04 18:01
As it is stated in the readme

> This extension is **not published on any other browsers currently**. Roblox+ is not available on Firefox, Edge, or other browsers. **Please do not download extensions that claim to this one on other browsers, they are not made by me.**

this extension is fake, please close the issue if you have no more questions

**Closed as completed** 2022-01-11 00:23 UTC
